apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: userRole
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "deployments"]
    verbs: ["create", "get", "list", "delete"]